/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarySearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class BinarySearchTest {
    @Test
    public void testBinarySearch_exists() {
        BinarySearch testingClass = new BinarySearch();
        int input[] = {4,8,15,16,23,42};
        int searchKey = 15;
        int expectedOutput = 2;
        assertEquals("binarySearch should return the index of the search key", expectedOutput, testingClass.binarySearch(input, searchKey));
    }

    @Test
    public void testBinarySearch_notExists() {
        BinarySearch testingClass = new BinarySearch();
        int input[] = {11,22,33,44,55,66,77};
        int searchKey = 90;
        int expectedOutput = -1;
        assertEquals("binarySearch should return the index of the search key", expectedOutput, testingClass.binarySearch(input, searchKey));
    }

    @Test
    public void testBinarySearch_duplicates() {
        BinarySearch testingClass = new BinarySearch();
        int input[] = {5, 5, 5, 5, 5, 5, 5};
        int searchKey = 5;
        int expectedOutput = input.length/2;
        assertEquals("binarySearch should return the index of the search key", expectedOutput, testingClass.binarySearch(input, searchKey));
    }

    @Test
    public void testBinarySearch_biggerArrays() {
        BinarySearch testingClass = new BinarySearch();
        int input[] = testingClass.generatArr(10000);
        int searchKey = 990;
        int expectedOutput = 990;
        assertEquals("binarySearch should return the index of the search key", expectedOutput, testingClass.binarySearch(input, searchKey));
    }

    @Test
    public void testBinarySearch_biggerArrays_notExist() {
        BinarySearch testingClass = new BinarySearch();
        int input[] = testingClass.generatArr(10000);
        int searchKey = 10001;
        int expectedOutput = -1;
        assertEquals("binarySearch should return the index of the search key", expectedOutput, testingClass.binarySearch(input, searchKey));
    }

}
